### ISSUE TITLE
冒昧请问一下大佬

### ISSUE THREAD

**Issue by Noelleqin** [HIllya51/YU_NO_re_chs#1]
请问一下大佬。我把补丁解压，文件夹内容复制到steam版游戏目录后，使用游戏原有的启动文件运行游戏依然是日文。想请问一下是我的操作有问题还是yuno重制版存在别的版本？因为补丁内并没有看见exe文件，我没有接触过，并且自行搜索尝试多时均没有结果，所以才冒昧请教，如有打扰十分抱歉！
![Screenshot](https://github.com/HIllya51/YU_NO_re_chs/assets/94843685/11f8444a-ff5c-4924-a507-f1c0eabdac05)

**Comment by HIllya51** [comment]
典中典之下载源代码

https://github.com/HIllya51/YU_NO_re_chs/releases/download/1/yuno.zip  这个才是补丁。
