### ISSUE TITLE
补充汉化

### ISSUE THREAD

**Issue by lqlqwq** [HIllya51/YU_NO_re_chs#4]
绯月帖子太久没法回复了
补充翻译还缺人吗  正文最近不一定有空，但是UI有些JF的玩起来太难受了，可以帮忙汉化一下

**Comment by HIllya51** [comment]
我们目前正在做【炼狱月狂病FHD】的汉化，计划是完成炼狱后去搞这一作呢。如果您希望参与这一作的汉化的话，可以给我你的QQ联系

**Comment by lqlqwq** [comment]
670141396
